-- Catálogos iniciales: las mismas listas desplegables que tenía el Excel.
-- Se ordenan alfabéticamente (en el Excel el orden era el histórico de altas).
-- "España" no estaba en la lista original pero 3 filas lo usaban: se incluye
-- para no perder ese dato al migrar.
insert into public.catalog_options (kind, value, position) values
  ('region','Andorra',0),
  ('region','ES-Andalucia',1),
  ('region','ES-Aragon',2),
  ('region','ES-Baleares',3),
  ('region','ES-Canarias',4),
  ('region','ES-Castilla Leon',5),
  ('region','ES-Castilla Mancha',6),
  ('region','ES-Cataluña',7),
  ('region','ES-Com.Valenciana',8),
  ('region','ES-Extremadura',9),
  ('region','ES-Galicia',10),
  ('region','ES-General',11),
  ('region','ES-Internacional',12),
  ('region','ES-Madrid',13),
  ('region','ES-Murcia',14),
  ('region','ES-Navarra',15),
  ('region','ES-País Vasco',16),
  ('region','ES-Rioja',17),
  ('region','España',18),
  ('region','PT-Lisboa',19),
  ('region','PT-Oporto',20),
  ('region','PT-Other',21),
  ('sector','Adm. Pública',0),
  ('sector','Aerolíneas',1),
  ('sector','Alimentación',2),
  ('sector','Automoción',3),
  ('sector','Banca',4),
  ('sector','Construcción',5),
  ('sector','Educación',6),
  ('sector','Energía',7),
  ('sector','Farma',8),
  ('sector','Hospitales',9),
  ('sector','Hoteles',10),
  ('sector','Juego',11),
  ('sector','Legal',12),
  ('sector','Manufactura',13),
  ('sector','Media',14),
  ('sector','Retail',15),
  ('sector','Salud',16),
  ('sector','Seguros',17),
  ('sector','Servicios',18),
  ('sector','Tecnología',19),
  ('sector','Telecom',20),
  ('sector','Textil',21),
  ('sector','Transporte',22),
  ('sector','Travel',23)
on conflict (kind, value) do nothing;
